# Generated by Django 5.2.8 on 2025-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='about/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Hello, I'm SunnyCode", max_length=200)),
                ('subtitle', models.CharField(default='Software Engineer & DevOps Specialist', max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
