# Generated by Django 5.2.8 on 2025-12-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
